### ISSUE TITLE
Runtime error for montserrat-32 font file

### ISSUE THREAD

**Issue by Taikatou** [craftworkgames/Samples.Extended#8]
Im getting the same bug as this https://github.com/craftworkgames/Samples.Extended/issues/5. I am using the newest version of the samples. Any idea what could be wrong? (I am new to Monogame extended)

**Comment by craftworkgames** [comment]
Yep. This issue is almost certainly because MonoGame 3.5 isn't compatible with MonoGame.Extended 0.4.64.

We haven't actually released the next version of MonoGame.Extended yet, but it's working correctly in the [`develop` branch](https://github.com/craftworkgames/MonoGame.Extended). 

All of these samples have also been moved into `develop` as "demos". You're best option is to [build from source](https://github.com/craftworkgames/MonoGame.Extended/wiki/Building-MonoGame.Extended-from-source) and run them from there.

We'll probably drop this samples repository to be honest. It hasn't worked as well as I'd hoped. I'm considering a few other options for delivering the demos in the future.

Hopefully moving forward we won't see these types of issues come up anymore. There was a number of breaking changes between MonoGame 3.4 and 3.5 that made things really difficult for us;  particularly with the Pipeline tool. Now the Pipeline is a little more stable things are working a lot better.

**Comment by Taikatou** [comment]
@craftworkgames Awesome thank you so much. Really the work you guys are doing. :)

**Comment by Taikatou** [comment]
All set up, thank you for the help. :)
